services:
  _defaults:
    public: true

  prestashop.module.smailyforprestashop.controller.opt_in_controller:
    class: PrestaShop\Module\SmailyForPrestaShop\Controller\OptInController
    arguments: ["@prestashop.adapter.legacy.configuration"]

  prestashop.module.smailyforprestashop.controller.abandoned_cart_controller:
   class: PrestaShop\Module\SmailyForPrestaShop\Controller\AbandonedCartController
   arguments:
   - '@prestashop.adapter.legacy.configuration'

  prestashop.module.smailyforprestashop.controller.customer_sync_controller:
    class: PrestaShop\Module\SmailyForPrestaShop\Controller\CustomerSyncController
    arguments:
    - '@prestashop.adapter.legacy.configuration'

  prestashop.module.smailyforprestashop.controller.rss_feed_controller:
    class: PrestaShop\Module\SmailyForPrestaShop\Controller\RssFeedController
