services:
  _defaults:
    public: true

  prestashop.module.smailyforprestashop.front.rss_feed_product_repository:
    class: PrestaShop\Module\SmailyForPrestaShop\Repository\RssFeedProductsRepository
