smailyforprestashop_module_configuration:
  path: /smailyforprestashop/configuration
  methods: [GET, POST]
  defaults:
    _controller: PrestaShop\Module\SmailyForPrestaShop\Controller\ModuleConfigurationController::index
    _legacy_controller: SmailyForPrestaShopConfiguration
    _legacy_link: SmailyForPrestaShopConfiguration
