version: '3.7'

services:
  prestashop:
    container_name: prestashop
    image: sendsmaily/prestashop
    build:
      context: .
      args:
        - username
        - user_id
        - group
        - group_id
    ports:
      - 8080:80
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=db
      - DB_USER=db_user
      - DB_PASSWD=db_password
      - DB_NAME=prestashop
    volumes:
      - prestashop-data:/var/www/html
      - ../.:/var/www/html/modules/smailyforprestashop
    depends_on:
    - db

  db:
    container_name: prestashop_db
    image: mysql:5.7
    environment:
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - MYSQL_ROOT_PASSWORD=db_password
      - MYSQL_DATABASE=prestashop
    volumes:
      - prestashop-db-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    environment:
      - PMA_HOST=db
      - PMA_USER=db_user
      - PMA_PASSWORD=db_password

volumes:
  prestashop-data:
  prestashop-db-data:
